try{
    hello();
}catch (error){
    console.log('error',error);
}


try{
    anotherFuncton();
}catch{
    console.log('error');
}